name = "kdzu-org-worker"
main = "dist/_worker.js/index.js"
account_id = "38b2250cde779e4a92c63d139be80a9c"
compatibility_date = "2024-06-01"

# Use workers_dev for local/dev, and routes for production
[env.dev]
workers_dev = true

[env.production]
workers_dev = false
routes = ["kdzu.org/*", "www.kdzu.org/*"]

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "kdzu-static"
preview_bucket_name = "kdzu-static"