name = "kdzu-org-worker"
main = "static-proxy-worker.js"
compatibility_flags = ["nodejs_compat"]
account_id = "38b2250cde779e4a92c63d139be80a9c"
compatibility_date = "2024-09-23"

# Use workers_dev for local/dev, and routes for production
[env.dev]
workers_dev = true

[env.production]
workers_dev = false
routes = [
  "static.kdzu.org/*"
]
r2_buckets = [
  { binding = "KDZU_STATIC", bucket_name = "kdzu-static" }
]

[observability.logs]
enabled = true