name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        
      - name: Upload assets to R2
        run: |
          find dist/_astro -type f | while read file; do
            npx wrangler r2 object put kdzu-static/"_astro/${file#dist/_astro/}" --file "$file"
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Upload public files to R2
        run: |
          find public -type f | while read file; do
            npx wrangler r2 object put kdzu-static/"${file#public/}" --file "$file"
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy main Astro site to Cloudflare Workers
        run: npx wrangler deploy --config wrangler-site.toml --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}